### ISSUE TITLE
page bounces up-down for many times

### ISSUE THREAD

**Issue by JasonCareter** [wangyukun-hxb/react-native-scroll-head-tab-view#6]
device: iPhone 12
react-native version: 0.63.2

I got three flatlist in tableview.All of theirs content is empty.
When my finger flipped down from center area of header at the first tab , the page kept bouncing up-down until I switched to another page.
Any idea on this , guys ?

**Comment by yasin-wang** [comment]
fix onContentSizeChange loop mensurate in tabview

**Comment by Shik1997** [comment]
> fix onContentSizeChange loop mensurate in tabview
i have  this problem too ...Please tell me how to solve it ?

**Comment by Shik1997** [comment]
> fix onContentSizeChange loop mensurate in tabview

Could you publish new version 1.0.5 ? i just see 1.0.3 in NPM

**Comment by yasin-wang** [comment]
I updated the version
